<h2>Editar Transacción</h2>

<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."transacciones/editar"; ?>" method="POST">

            <input type="hidden" name="id" class="form-control" value="<?php echo $this->transacciones["id"]; ?>">

            <label for="cuenta">Cuenta</label>
            <select name="account_id" class="form-control">
                <?php foreach ($this->cuentas as $cuenta) {
                    if ($this->transacciones["account_id"]==$cuenta["id"]) { ?>
                    <option selected value="<?php echo $cuenta["id"]; ?>"><?php echo $cuenta["name"]; ?></option>
                <?php }else{ ?>
                    <option value="<?php echo $cuenta["id"]; ?>"><?php echo $cuenta["name"]; ?></option>
                <?php } } ?>
            </select>

            <label for="categoria">Categoria</label>
            <select name="category_id" class="form-control">
                <?php foreach ($this->categorias as $categoria) {
                     if ($this->transacciones["category_id"]==$categoria["id"]) {?>
                    <option selected value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["name"]; ?></option>
                <?php }else{ ?>
                    <option value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["name"]; ?></option>
                <?php } } ?>
            </select>
    </div>
    <div class="col-sm-6">

        <label for="descripcion">Descripción</label>
        <textarea name="description" class="form-control"><?php echo $this->transacciones["description"]; ?></textarea>

        <label for="fecha">Fecha</label>
        <input type="date" name="date" class="form-control" value="<?php echo $this->transacciones["date"]; ?>">

        <label for="cantidad">Cantidad</label>
        <input type="number" name="amount" step="0.01" class="form-control" value="<?php echo $this->transacciones["amount"]; ?>">

        <br>

        <a href="<?php echo APP_URL."transacciones/index"; ?>" >
            <button type="button" class="btn btn-default">Cancelar</button>
        </a>
        <input type="submit" class="btn btn-primary" value="Guardar Tarea">

        </form>
    </div>
</div>