<div class="row">
    <div class="col-sm-12">
        <h2>Lista de transacciones</h2>
        <div class="">
            <a href="<?php echo APP_URL."transacciones/agregar"; ?>" >
                <button type="button" class="waves-effect waves-light btn-small">
                Agregar Transacción
                </button>
            </a>
            <a href="<?php echo APP_URL."categorias/index"; ?>">
                <button type="button" class="waves-effect waves-light btn-small">
                Ver Categorías
                </button>
            </a>
            <a href="<?php echo APP_URL."cuentas/index"; ?>">
                <button type="button" class="waves-effect waves-light btn-small">
                Ver Cuentas
                </button>
            </a>
        </div>
        <br><br>

        <div class="table-responsive">
            <table class="table table-bordered table-hover table-condensed responsive-table table-dark">
                <tr>
                    <th>ID</th>
                    <th>Cuenta</th>
                    <th>Categoria</th>
                    <th>Descripción</th>
                    <th>Fecha</th>
                    <th>Cantidad</th>
                    <th>Acción</th>
                </tr>
                <?php $balance = 0;
                $ingreso = 0;
                $egreso = 0;
                foreach ($this->transacciones as $transaccion): ?>
                    <tr>
                        <td><?php echo $transaccion["t"]["id"]; ?></td>
                        <td><?php echo $transaccion["a"]["name"]; ?></td>
                        <td><?php echo $transaccion["c"]["name"]; ?></td>
                        <td><?php echo $transaccion["t"]["description"]; ?></td>
                        <td><?php
                            $date = new DateTime($transaccion["t"]["date"]);
                            echo $date->format('d/m/Y'); ?></td>
                        <td>$<?php
                                if ($transaccion["t"]["amount"] > 0){
                                    $balance = $balance + $transaccion["t"]["amount"];
                                    echo "<label style='color: green'>".$transaccion["t"]["amount"]."</label>";
                                }else{
                                    $balance = $balance - $transaccion["t"]["amount"];
                                    echo "<label style='color: red'>".$transaccion["t"]["amount"]."</label>"; }
                            ?></td>
                        <td> <a href="<?php echo APP_URL."transacciones/editar/".$transaccion["t"]["id"]; ?>" class="btn btn-primary">editar</a>
                            <a href="<?php echo APP_URL."transacciones/eliminar/".$transaccion["t"]["id"]; ?>" class="btn btn-danger confirmation">borrar</a>
                    </tr>
                    <?php if ($transaccion["t"]["amount"] > 0) {
                        $ingreso = $transaccion["t"]["amount"] + $ingreso;
                    }else{
                        $egreso = $transaccion["t"]["amount"] + $egreso;
                    } ?>
                <?php endforeach; ?>
            </table>
            <br>
            <?php echo "<label class='right' style='color: blue'>".$balance."</label><label class='right'>Balance: $ </label><br>"; ?>
            <?php echo "<label class='right' style='color: green'>".$ingreso."</label><label class='right'>Ingreso:  $</label><br>"; ?>
            <?php echo "<label class='right' style='color: red'>".$egreso."</label><label class='right'>Egreso: $ </label>"; ?>
        </div>
    </div>
</div>