<h2>Editar categoria</h2>

<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."categorias/editar"; ?>" method="POST">

            <input type="hidden" name="id" class="form-control" value="<?php echo $this->categorias["id"]; ?>">
            <label for="nombre">Nombre</label>

            <input type="text" name="name" class="form-control" value="<?php echo $this->categorias["name"]; ?>">
            <br>

            <a href="<?php echo APP_URL."categorias/index"; ?>" >
                <button type="button" class="btn btn-default">Cancelar</button>
            </a>
            <input type="submit" class="btn btn-primary" value="Guardar Categoria">
    </div>
        </form>
</div>
