<div class="container">
<div class="row">
    <div class="col-sm-12">
        <h2>Lista de categorias</h2>
            <div class="">
                <a href="<?php echo APP_URL."transacciones/index"; ?>" >
                    <button type="button" class="waves-effect waves-light btn-small">
                     Transacciones
                    </button>
                </a>
                <a href="<?php echo APP_URL."categorias/agregar"; ?>" class="right">
                    <button type="button" class="waves-effect waves-light btn-small">
                    Agregar Categoría
                    </button>
                </a>
            </div>
            <div class="">

            </div>
        <br><br>
        <div class="table-responsive centered">
            <table class="table table-hover table-bordered table-condensed responsive-table table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Acción</th>
                </tr>
                <?php foreach ($this->categorias as $categoria): ?>
                    <tr>
                        <td><?php echo $categoria["id"]; ?></td>
                        <td><?php echo $categoria["name"]; ?></td>
                        <td> <a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>" class="btn btn-primary">editar</a>
                             <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>" class="confirmation btn btn-danger">borrar</a>
                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
    </div>
</div>
</div>