<h2>Agregar Cuenta</h2>

<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."cuentas/agregar"; ?>" method="POST">

            <label for="nombre">Nombre</label>
            <input type="text" name="name" class="form-control">
            <br>

            <a href="<?php echo APP_URL."cuentas/index"; ?>" >
                <button type="button" class="btn btn-default">Cancelar</button>
            </a>
            <input type="submit" class="btn btn-primary" value="Guardar Cuenta">
    </div>

    </form>
</div>