<h2>Editar cuenta</h2>

<div class="row">
    <div class="col-sm-6">
        <form action="<?php echo APP_URL."cuentas/editar"; ?>" method="POST">

            <input type="hidden" name="id" class="form-control" value="<?php echo $this->cuentas["id"]; ?>">
            <label for="nombre">Nombre</label>

            <input type="text" name="name" class="form-control" value="<?php echo $this->cuentas["name"]; ?>">
            <br>

            <a href="<?php echo APP_URL."cuentas/index"; ?>" >
                <button type="button" class="btn btn-default">Cancelar</button>
            </a>
            <input type="submit" class="btn btn-primary" value="Guardar Categoria">
    </div>
    </form>
</div>