<div class="row">
    <div class="col-sm-12">
        <h2>Lista de cuentas</h2>
        <div class="">
            <a href="<?php echo APP_URL."transacciones/index"; ?>" >
                <button type="button" class="waves-effect waves-light btn-small">
                    Transacciones
                </button>
            </a>
            <a href="<?php echo APP_URL."cuentas/agregar"; ?>" class="right">
                <button type="button" class="waves-effect waves-light btn-small">
                    Agregar Cuenta
                </button>
            </a>
        </div>
        <div class="">

        </div>
        <br><br>
        <div class="table-responsive">
            <table class="table table-hover table-bordered table-condensed responsive-table table-dark">
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Acción</th>
                </tr>
                <?php foreach ($this->cuentas as $cuenta): ?>
                    <tr>
                        <td><?php echo $cuenta["id"]; ?></td>
                        <td><?php echo $cuenta["name"]; ?></td>
                        <td> <a href="<?php echo APP_URL."cuentas/editar/".$cuenta["id"]; ?>" class="btn btn-primary">edit</a>
                            <a href="<?php echo APP_URL."cuentas/eliminar/".$cuenta["id"]; ?>" class="confirmation btn btn-danger">delete</a>
                    </tr>
                <?php endforeach; ?>

            </table>
        </div>
    </div>
</div>
